/**
 * @generated
 * @file NavbarPrimary (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://anderson-group-stage.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Icon from "./webflow_modules/Icon/components/Icon";
import Link from "./webflow_modules/Basic/components/Link";
import List from "./webflow_modules/Basic/components/List";
import ListItem from "./webflow_modules/Basic/components/ListItem";
import NavbarBrand from "./webflow_modules/Navbar/components/NavbarBrand";
import NavbarButton from "./webflow_modules/Navbar/components/NavbarButton";
import NavbarMenu from "./webflow_modules/Navbar/components/NavbarMenu";
import NavbarWrapper from "./webflow_modules/Navbar/components/NavbarWrapper";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link NavbarPrimary}
 */
export type NavbarPrimaryProps = {};

/**
 * NavbarPrimary
 *
 * @see {@link https://anderson-group-stage.design.webflow.com | Source site in Webflow}
 */
export function NavbarPrimary({}: NavbarPrimaryProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"navbar-logo-left"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <NavbarWrapper
          className={"navbar-logo-left-container"}
          config={{
            easing: "ease",
            easing2: "ease",
            duration: 400,
            docHeight: false,
            noScroll: false,
            animation: "default",
            collapse: "medium",
          }}
          tag={"div"}
        >
          <Block className={"container"} tag={"div"}>
            <Block className={"navbar-wrapper"} tag={"div"}>
              <NavbarBrand
                className={"navbar-brand"}
                options={{
                  href: "#",
                }}
              >
                <Block tag={"div"}>{"Anderson Group Real Estate"}</Block>
              </NavbarBrand>
              <NavbarMenu
                className={"nav-menu-wrapper"}
                role={"navigation"}
                tag={"nav"}
              >
                <List className={"nav-menu-two"} tag={"ul"} unstyled={true}>
                  <ListItem>
                    <Link
                      button={false}
                      className={"nav-link"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"About"}
                    </Link>
                  </ListItem>
                  <ListItem>
                    <Link
                      button={false}
                      className={"nav-link"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Services"}
                    </Link>
                  </ListItem>
                  <ListItem>
                    <Link
                      button={false}
                      className={"nav-link"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Projects"}
                    </Link>
                  </ListItem>
                  <ListItem>
                    <Link
                      button={false}
                      className={"nav-link"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Gallery"}
                    </Link>
                  </ListItem>
                  <ListItem>
                    <Link
                      button={false}
                      className={"nav-link"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Reviews"}
                    </Link>
                  </ListItem>
                  <ListItem>
                    <Link
                      button={false}
                      className={"nav-link"}
                      options={{
                        href: "#",
                      }}
                    >
                      {"Contact"}
                    </Link>
                  </ListItem>
                  <ListItem>
                    <Link
                      button={true}
                      className={"primary-button is-nav"}
                      options={{
                        href: "/find-an-agent",
                      }}
                    >
                      {"Find an Agent"}
                    </Link>
                  </ListItem>
                </List>
              </NavbarMenu>
              <NavbarButton className={"menu-button"} tag={"div"}>
                <Icon
                  widget={{
                    type: "icon",
                    icon: "nav-menu",
                  }}
                />
              </NavbarButton>
            </Block>
          </Block>
        </NavbarWrapper>
      </Section>
    </div>
  );
}
